### ISSUE TITLE
Huawei r4875g1

### ISSUE THREAD

**Issue by DJJo14** [clowrey/ESPhome-YAML#1]
Thanks for you esphome code for the Huawei r4875g1. I am going to use it in a future project of mine. 
 
But I have a question do you have 1 device that uses 2 can address. or do you have 2 Huawei r4875g1?

End how is you code working

**Comment by clowrey** [comment]
I have 3 of them even, was going to use three phase and or more power than one can deliver.

**Comment by DJJo14** [comment]
Did your code work? 
How did you set the CAN ID's?

**Comment by clowrey** [comment]
Yes it worked. They are automatically set when more than one on the same bus I believe. But you'll have to figure it out..

**Comment by DJJo14** [comment]
thanks for the info
